// Auto-generated from the TrustFlow design (screen "dispute"). Do not hand-edit.
export const html = `<div class="fscroll" style="width:366px; height:820px; border-radius:42px; overflow-y:auto; overflow-x:hidden; position:relative; background:#0B0B0D;">
          <div style="height:44px; display:flex; align-items:center; justify-content:space-between; padding:0 26px; font-size:13px; font-weight:600;"><span>9:41</span><span style="opacity:.7;">▂▃▄ ᯤ ▮</span></div>
          <div style="padding:8px 22px 0; display:flex; align-items:center; gap:14px;"><div class="navbtn" data-nav="timeline" style="width:40px; height:40px; border-radius:12px; background:#17171a; display:flex; align-items:center; justify-content:center;"><svg width="18" height="18" viewBox="0 0 24 24" stroke="#fff" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M15 18l-6-6 6-6"/></svg></div><h2 style="font-size:20px; font-weight:800; letter-spacing:-.02em;">Dispute</h2></div>
          <!-- two sides -->
          <div style="padding:14px 22px 0;">
            <div style="border-radius:16px; background:#141416; border:1px solid #202024; padding:14px;"><div style="display:flex; align-items:center; gap:8px; margin-bottom:8px;"><div style="width:24px; height:24px; border-radius:50%; background:#E4144F; display:flex; align-items:center; justify-content:center; font-size:11px; font-weight:800;">A</div><span style="font-size:13px; font-weight:700;">Buyer's claim</span></div><p style="font-size:13px; color:#c8c8ce; line-height:1.5;">"Screen has a dead pixel line, not shown in the listing photos."</p><div style="margin-top:10px; display:flex; gap:8px;"><div style="width:56px; height:56px; border-radius:10px; background:repeating-linear-gradient(45deg,#1e1e22,#1e1e22 6px,#242429 6px,#242429 12px); display:flex; align-items:center; justify-content:center; font-size:9px; color:#6d6d74; text-align:center;">photo</div><div style="width:56px; height:56px; border-radius:10px; background:repeating-linear-gradient(45deg,#1e1e22,#1e1e22 6px,#242429 6px,#242429 12px); display:flex; align-items:center; justify-content:center; font-size:9px; color:#6d6d74;">video</div></div></div>
            <div style="margin-top:10px; border-radius:16px; background:#141416; border:1px solid #202024; padding:14px;"><div style="display:flex; align-items:center; gap:8px; margin-bottom:8px;"><div style="width:24px; height:24px; border-radius:50%; background:#7C3AED; display:flex; align-items:center; justify-content:center; font-size:11px; font-weight:800;">C</div><span style="font-size:13px; font-weight:700;">Seller's response</span></div><p style="font-size:13px; color:#c8c8ce; line-height:1.5;">"Item was fine when shipped. Willing to refund part of it."</p><div style="margin-top:10px; display:flex; gap:8px;"><div style="width:56px; height:56px; border-radius:10px; background:repeating-linear-gradient(45deg,#1e1e22,#1e1e22 6px,#242429 6px,#242429 12px); display:flex; align-items:center; justify-content:center; font-size:9px; color:#6d6d74;">photo</div></div></div>
          </div>
          <!-- AI MEDIATOR card -->
          <div style="margin:20px 22px 24px; border-radius:22px; padding:2px; background:linear-gradient(135deg,#7C3AED,#C026D3,#E4144F);">
            <div style="border-radius:20px; background:#120a16; padding:20px;">
              <div style="display:flex; align-items:center; gap:10px;"><div style="width:34px; height:34px; border-radius:11px; background:radial-gradient(circle at 35% 30%, #d9a6ff, #7C3AED); display:flex; align-items:center; justify-content:center;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#fff" stroke-width="1.9"><path d="M12 3v4M6 7l2 2M18 7l-2 2M4 21v-4a8 8 0 0 1 16 0v4" stroke-linecap="round"/><circle cx="12" cy="13" r="1.6" fill="#fff"/></svg></div><div><div style="font-size:11px; color:#c99cff; font-weight:700; letter-spacing:.04em;">AI MEDIATOR · NEUTRAL</div><div style="font-size:15px; font-weight:800;">Recommendation</div></div></div>
              <div style="margin-top:16px; display:flex; align-items:center; gap:12px;"><div data-bind="decisionLabel" style="font-size:26px; font-weight:800; letter-spacing:-.02em; color:#E0A23C;">PARTIAL REFUND</div></div>
              <div style="margin-top:14px; display:flex; gap:10px;"><div style="flex:1; text-align:center; padding:12px 0; border-radius:12px; background:rgba(52,208,126,.1);"><div style="font-size:11px; color:#9A9AA0;">To seller</div><div data-bind="toSeller" style="font-size:17px; font-weight:800; color:#34D07E; margin-top:2px;">₦330,000</div></div><div style="flex:1; text-align:center; padding:12px 0; border-radius:12px; background:rgba(228,20,79,.1);"><div style="font-size:11px; color:#9A9AA0;">Refund buyer</div><div data-bind="toBuyer" style="font-size:17px; font-weight:800; color:#ff8fa8; margin-top:2px;">₦120,000</div></div></div>
              <p style="margin-top:16px; font-size:13px; line-height:1.55; color:#c8c8ce;"><b style="color:#fff;">Why:</b> <span data-bind="rationale">Buyer's video confirms a real screen defect, but the item is genuine and usable. A ~27% price reduction matches the repair cost for this model, fair to both sides.</span></p>
              <div style="margin-top:16px; display:flex; gap:10px;"><div style="flex:1; height:48px; border-radius:12px; background:#E4144F; display:flex; align-items:center; justify-content:center; font-weight:700; font-size:14px;">Accept</div><div style="flex:1; height:48px; border-radius:12px; background:rgba(255,255,255,.06); border:1px solid #33333a; display:flex; align-items:center; justify-content:center; font-weight:700; font-size:14px; color:#e9e9ee;">Escalate to human</div></div>
            </div>
          </div>
        </div>`;
