// Dispute — rebuilt light (v2). Two sides, then the AI mediator's ruling on a
// navy hero card. Bound values (decisionLabel / toSeller / toBuyer / rationale)
// come from the real AI judge in dispute/page.tsx. Hooks unchanged.
export const html = `<div class="fscroll" style="width:100%; min-height:100dvh; overflow-x:hidden; position:relative; background:#F8FAFC; color:#0F172A; padding-bottom:28px;">
          <div style="height:44px; display:flex; align-items:center; justify-content:space-between; padding:0 26px; font-size:13px; font-weight:600;"><span>9:41</span><span style="opacity:.5;">▂▃▄ ᯤ ▮</span></div>
          <div style="padding:8px 20px 0; display:flex; align-items:center; gap:14px;"><div class="navbtn" data-nav="timeline" style="width:40px; height:40px; border-radius:12px; background:#fff; border:1px solid #E6EAF0; box-shadow:0 1px 2px rgba(15,23,42,.05); display:flex; align-items:center; justify-content:center;"><svg width="18" height="18" viewBox="0 0 24 24" stroke="#0F172A" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M15 18l-6-6 6-6"/></svg></div><h2 style="font-size:20px; font-weight:700; letter-spacing:-.02em;">Dispute</h2></div>
          <!-- two sides -->
          <div style="padding:14px 20px 0;">
            <div style="border-radius:16px; background:#fff; border:1px solid #E6EAF0; box-shadow:0 1px 2px rgba(15,23,42,.05); padding:15px;"><div style="display:flex; align-items:center; gap:8px; margin-bottom:8px;"><div style="width:24px; height:24px; border-radius:50%; background:#0F172A; color:#fff; display:flex; align-items:center; justify-content:center; font-size:10px; font-weight:700;">YOU</div><span style="font-size:13px; font-weight:600;">Buyer's claim</span></div><p style="font-size:13px; color:#475569; line-height:1.5;">"Screen has a dead pixel line, not shown in the listing photos."</p><div style="margin-top:10px; display:flex; gap:8px;"><div style="width:56px; height:56px; border-radius:10px; background:#F1F5F9; border:1px dashed #CBD5E1; display:flex; align-items:center; justify-content:center; font-size:9px; color:#94A3B8; text-align:center;">Photo</div><div style="width:56px; height:56px; border-radius:10px; background:#F1F5F9; border:1px dashed #CBD5E1; display:flex; align-items:center; justify-content:center; font-size:9px; color:#94A3B8;">Video</div></div></div>
            <div style="margin-top:10px; border-radius:16px; background:#fff; border:1px solid #E6EAF0; box-shadow:0 1px 2px rgba(15,23,42,.05); padding:15px;"><div style="display:flex; align-items:center; gap:8px; margin-bottom:8px;"><div style="width:24px; height:24px; border-radius:50%; background:#E6EAF0; color:#334155; display:flex; align-items:center; justify-content:center; font-size:11px; font-weight:700;">S</div><span style="font-size:13px; font-weight:600;">Seller's response</span></div><p style="font-size:13px; color:#475569; line-height:1.5;">"Item was fine when shipped. Willing to refund part of it."</p><div style="margin-top:10px; display:flex; gap:8px;"><div style="width:56px; height:56px; border-radius:10px; background:#F1F5F9; border:1px dashed #CBD5E1; display:flex; align-items:center; justify-content:center; font-size:9px; color:#94A3B8;">Photo</div></div></div>
          </div>
          <!-- AI MEDIATOR card (navy) -->
          <div style="margin:20px 20px 0; border-radius:22px; background:radial-gradient(120% 130% at 85% 0%, #14304A 0%, #0F172A 58%); padding:22px; box-shadow:0 24px 48px -22px rgba(15,23,42,.5);">
            <div style="display:flex; align-items:center; gap:10px;"><div style="width:34px; height:34px; border-radius:11px; background:rgba(16,185,129,.16); display:flex; align-items:center; justify-content:center;"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="#6EE7B7" stroke-width="1.9"><path d="M12 3v4M6 7l2 2M18 7l-2 2M4 21v-4a8 8 0 0 1 16 0v4" stroke-linecap="round"/><circle cx="12" cy="13" r="1.6" fill="#6EE7B7"/></svg></div><div><div style="font-size:11px; color:#6EE7B7; font-weight:600; letter-spacing:.06em;">AI MEDIATOR · NEUTRAL</div><div style="font-size:15px; font-weight:700; color:#fff;">Recommendation</div></div></div>
            <div data-bind="decisionLabel" style="margin-top:16px; font-size:26px; font-weight:700; letter-spacing:-.02em; color:#fff;">PARTIAL REFUND</div>
            <div style="margin-top:14px; display:flex; gap:10px;"><div style="flex:1; text-align:center; padding:12px 0; border-radius:12px; background:rgba(16,185,129,.14); border:1px solid rgba(16,185,129,.28);"><div style="font-size:11px; color:#93A4BC;">To seller</div><div data-bind="toSeller" style="font-size:17px; font-weight:700; color:#6EE7B7; margin-top:2px; font-variant-numeric:tabular-nums;">₦330,000</div></div><div style="flex:1; text-align:center; padding:12px 0; border-radius:12px; background:rgba(251,191,36,.12); border:1px solid rgba(251,191,36,.28);"><div style="font-size:11px; color:#93A4BC;">Refund buyer</div><div data-bind="toBuyer" style="font-size:17px; font-weight:700; color:#FCD34D; margin-top:2px; font-variant-numeric:tabular-nums;">₦120,000</div></div></div>
            <p style="margin-top:16px; font-size:13px; line-height:1.55; color:#B7C4D8;"><b style="color:#fff;">Why:</b> <span data-bind="rationale">Buyer's video confirms a real screen defect, but the item is genuine and usable. A ~27% price reduction matches the repair cost for this model, fair to both sides.</span></p>
            <div style="margin-top:18px; display:flex; gap:10px;"><div class="navbtn" style="flex:1; height:48px; border-radius:12px; background:#059669; display:flex; align-items:center; justify-content:center; font-weight:600; font-size:14px; color:#fff;">Accept</div><div class="navbtn" style="flex:1; height:48px; border-radius:12px; background:rgba(255,255,255,.06); border:1px solid rgba(255,255,255,.16); display:flex; align-items:center; justify-content:center; font-weight:600; font-size:14px; color:#E2E8F0;">Escalate to human</div></div>
          </div>
        </div>`;
