// Auto-generated from the TrustFlow design (screen "timeline"). Do not hand-edit.
export const html = `<div class="fscroll" style="width:366px; height:820px; border-radius:42px; overflow-y:auto; overflow-x:hidden; position:relative; background:#0B0B0D;">
          <div style="height:44px; display:flex; align-items:center; justify-content:space-between; padding:0 26px; font-size:13px; font-weight:600;"><span>9:41</span><span style="opacity:.7;">▂▃▄ ᯤ ▮</span></div>
          <div style="padding:8px 22px 0; display:flex; align-items:center; gap:14px;"><div class="navbtn" data-nav="dashboard" style="width:40px; height:40px; border-radius:12px; background:#17171a; display:flex; align-items:center; justify-content:center;"><svg width="18" height="18" viewBox="0 0 24 24" stroke="#fff" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M15 18l-6-6 6-6"/></svg></div><h2 data-bind="title" style="font-size:18px; font-weight:800; letter-spacing:-.02em;">MacBook Air M2</h2></div>
          <!-- summary card -->
          <div style="margin:16px 22px 0; border-radius:20px; background:#141416; border:1px solid #202024; padding:18px;">
            <div style="display:flex; justify-content:space-between; align-items:center;"><div><div style="font-size:12px; color:#9A9AA0;">Amount in escrow</div><div data-bind="amount" style="font-size:26px; font-weight:800; letter-spacing:-.02em; margin-top:2px;">₦450,000</div></div><div style="display:inline-flex; align-items:center; gap:7px; padding:7px 12px; border-radius:999px; background:rgba(52,208,126,.15); color:#34D07E; font-size:12px; font-weight:700;"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#34D07E" stroke-width="2.4"><path d="M12 2l7 4v6c0 5-3 8-7 10-4-2-7-5-7-10V6z"/></svg><span data-bind="trustLine">Score 88 · Low risk</span></div></div>
            <div style="margin-top:16px; padding-top:16px; border-top:1px solid #202024; display:flex; justify-content:space-between; font-size:13px;"><div><div style="color:#9A9AA0;">Buyer</div><div data-bind="buyer" style="font-weight:600; margin-top:3px;">You</div></div><div style="text-align:right;"><div style="color:#9A9AA0;">Seller</div><div data-bind="seller" style="font-weight:600; margin-top:3px;">Chidi · +234 803…</div></div></div>
          </div>
          <!-- stepper (rendered from the deal's real timeline + status) -->
          <div style="margin:22px 22px 0; font-size:13px; font-weight:700; color:#9A9AA0;">PROGRESS</div>
          <div data-html="stepper" style="margin:14px 22px 0; padding-left:8px;"></div>
          <div data-html="actions" style="margin:8px 22px 24px;"><div class="navbtn" data-action="confirm" style="height:56px; border-radius:14px; background:#E4144F; display:flex; align-items:center; justify-content:center; gap:9px; font-weight:700; font-size:16px;"><svg width="17" height="17" viewBox="0 0 24 24" stroke="#fff" stroke-width="2.4" fill="none"><path d="M20 6 9 17l-5-5" stroke-linecap="round" stroke-linejoin="round"/></svg>Confirm Received</div><div class="navbtn" data-nav="dispute" style="margin-top:12px; height:56px; border-radius:14px; background:transparent; border:1px solid #33333a; display:flex; align-items:center; justify-content:center; font-weight:700; font-size:16px; color:#e9e9ee;">Open Dispute</div></div>
        </div>`;
