// Deal timeline — redesigned light. Summary card, progress stepper, and
// actions are all driven by the deal's real status (generators in
// timeline/page.tsx). Wiring hooks unchanged: data-bind title/amount/trustLine/
// buyer/seller, data-html stepper/actions, data-nav back.
export const html = `<div class="fscroll" style="width:100%; min-height:100dvh; overflow-x:hidden; position:relative; background:#F8FAFC; color:#0F172A; padding-bottom:28px;">
          <div style="height:44px; display:flex; align-items:center; justify-content:space-between; padding:0 26px; font-size:13px; font-weight:600;"><span>9:41</span><span style="opacity:.5;">▂▃▄ ᯤ ▮</span></div>
          <div style="padding:8px 20px 0; display:flex; align-items:center; gap:14px;"><div class="navbtn" data-nav="dashboard" style="width:40px; height:40px; border-radius:12px; background:#fff; border:1px solid #E6EAF0; box-shadow:0 1px 2px rgba(15,23,42,.05); display:flex; align-items:center; justify-content:center;"><svg width="18" height="18" viewBox="0 0 24 24" stroke="#0F172A" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M15 18l-6-6 6-6"/></svg></div><h2 data-bind="title" style="font-size:18px; font-weight:700; letter-spacing:-.02em;">Deal</h2></div>
          <!-- summary card -->
          <div style="margin:16px 20px 0; border-radius:20px; background:#fff; border:1px solid #E6EAF0; box-shadow:0 1px 2px rgba(15,23,42,.05); padding:18px;">
            <div style="display:flex; justify-content:space-between; align-items:center;"><div><div style="font-size:12px; color:#64748B;">Amount in escrow</div><div data-bind="amount" style="font-size:26px; font-weight:700; letter-spacing:-.02em; margin-top:2px; font-variant-numeric:tabular-nums;">₦0</div></div><div style="display:inline-flex; align-items:center; gap:7px; padding:7px 12px; border-radius:999px; background:#ECFDF5; border:1px solid #C7F0DE; color:#059669; font-size:12px; font-weight:600;"><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#059669" stroke-width="2"><path d="M12 2l7 4v6c0 5-3 8-7 10-4-2-7-5-7-10V6z"/></svg><span data-bind="trustLine">Not scored</span></div></div>
            <div style="margin-top:16px; padding-top:16px; border-top:1px solid #EEF2F6; display:flex; justify-content:space-between; font-size:13px;"><div><div style="color:#64748B;">Buyer</div><div data-bind="buyer" style="font-weight:600; margin-top:3px; color:#0F172A;">You</div></div><div style="text-align:right;"><div style="color:#64748B;">Seller</div><div data-bind="seller" style="font-weight:600; margin-top:3px; color:#0F172A;">Seller</div></div></div>
          </div>
          <!-- stepper -->
          <div style="margin:24px 20px 0; font-size:13px; font-weight:700; color:#64748B; letter-spacing:.02em;">PROGRESS</div>
          <div data-html="stepper" style="margin:14px 20px 0; padding-left:6px;"></div>
          <div data-html="actions" style="margin:8px 20px 0;"><div class="navbtn" data-action="confirm" style="height:56px; border-radius:15px; background:#059669; display:flex; align-items:center; justify-content:center; gap:9px; font-weight:600; font-size:16px; color:#fff; box-shadow:0 14px 26px -12px rgba(5,150,105,.55);"><svg width="17" height="17" viewBox="0 0 24 24" stroke="#fff" stroke-width="2.4" fill="none"><path d="M20 6 9 17l-5-5" stroke-linecap="round" stroke-linejoin="round"/></svg>Confirm received</div></div>
        </div>`;
