// Auto-generated from the TrustFlow design (screen "trust-high"). Do not hand-edit.
export const html = `<div class="fscroll" style="width:366px; height:820px; border-radius:42px; overflow-y:auto; overflow-x:hidden; position:relative; background:radial-gradient(120% 70% at 50% 0%, #2a0a0a 0%, #0B0B0D 55%);">
          <div style="height:44px; display:flex; align-items:center; justify-content:space-between; padding:0 26px; font-size:13px; font-weight:600;"><span>9:41</span><span style="opacity:.7;">▂▃▄ ᯤ ▮</span></div>
          <div style="padding:8px 22px 0; display:flex; align-items:center; gap:14px;"><div class="navbtn" data-nav="dashboard" style="width:40px; height:40px; border-radius:12px; background:rgba(255,255,255,.06); display:flex; align-items:center; justify-content:center;"><svg width="18" height="18" viewBox="0 0 24 24" stroke="#fff" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M15 18l-6-6 6-6"/></svg></div><h2 style="font-size:20px; font-weight:800; letter-spacing:-.02em;">Trust Score</h2></div>
          <div style="display:flex; flex-direction:column; align-items:center; margin-top:20px;">
            <div style="position:relative; width:210px; height:210px;">
              <div class="ring high" data-animate style="position:absolute; inset:0; border-radius:50%; background:conic-gradient(#FF4D4D calc(var(--p)*3.6deg), rgba(255,255,255,.07) 0); box-shadow:0 0 50px -6px rgba(255,77,77,.45); animation:pulseGlow 2s ease-in-out infinite;"></div>
              <div style="position:absolute; inset:16px; border-radius:50%; background:radial-gradient(circle at 38% 30%, #2a1414, #0B0B0D 70%); box-shadow:inset 0 6px 20px rgba(0,0,0,.7);"></div>
              <div style="position:absolute; top:34px; left:60px; width:70px; height:44px; border-radius:50%; background:radial-gradient(circle at 40% 30%, rgba(255,77,77,.35), transparent 70%); filter:blur(4px);"></div>
              <div style="position:absolute; inset:0; display:flex; flex-direction:column; align-items:center; justify-content:center;"><div class="score-num" data-countup="21" style="font-size:66px; font-weight:800; letter-spacing:-.05em; line-height:1; color:#fff;">0</div><div style="font-size:13px; color:#9A9AA0; margin-top:2px;">out of 100</div></div>
            </div>
            <div style="margin-top:18px; display:inline-flex; align-items:center; gap:8px; padding:9px 18px; border-radius:999px; background:rgba(255,77,77,.15); border:1px solid rgba(255,77,77,.45); color:#FF4D4D; font-size:14px; font-weight:800; letter-spacing:.02em;"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#FF4D4D" stroke-width="2.4"><path d="M12 9v4m0 4h.01M10.3 3.9 1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0z" stroke-linecap="round" stroke-linejoin="round"/></svg><span data-bind="riskLabel">HIGH RISK</span></div>
          </div>
          <div style="margin:22px 22px 0; padding:16px; border-radius:18px; background:rgba(255,77,77,.09); border:1px solid rgba(255,77,77,.3);"><p data-bind="headline" style="font-size:15px; line-height:1.5; color:#ffd4d4; font-weight:600;">Strong scam signals. We'd stop here — do not pay this seller until they prove they're real.</p></div>
          <div style="margin:20px 22px 0;"><div style="font-size:13px; font-weight:700; color:#9A9AA0; letter-spacing:.02em; margin-bottom:12px;">WHY WE FLAGGED IT</div>
            <div class="flag" data-animate style="display:flex; gap:12px; align-items:flex-start; padding:12px 0; border-bottom:1px solid #1a1a1e;"><div style="width:26px; height:26px; border-radius:8px; background:rgba(255,77,77,.15); display:flex; align-items:center; justify-content:center; flex-shrink:0;"><svg width="15" height="15" viewBox="0 0 24 24" stroke="#FF4D4D" stroke-width="2.6" fill="none"><path d="M12 8v5m0 3h.01" stroke-linecap="round"/></svg></div><div style="font-size:14px; color:#e9e9ee; line-height:1.4;">Account is only <b>2 days old</b>, no verified identity</div></div>
            <div class="flag" data-animate style="display:flex; gap:12px; align-items:flex-start; padding:12px 0; border-bottom:1px solid #1a1a1e;"><div style="width:26px; height:26px; border-radius:8px; background:rgba(255,77,77,.15); display:flex; align-items:center; justify-content:center; flex-shrink:0;"><svg width="15" height="15" viewBox="0 0 24 24" stroke="#FF4D4D" stroke-width="2.6" fill="none"><path d="M12 8v5m0 3h.01" stroke-linecap="round"/></svg></div><div style="font-size:14px; color:#e9e9ee; line-height:1.4;">Pressure language: <b>"pay now, it's the last one"</b></div></div>
            <div class="flag" data-animate style="display:flex; gap:12px; align-items:flex-start; padding:12px 0; border-bottom:1px solid #1a1a1e;"><div style="width:26px; height:26px; border-radius:8px; background:rgba(255,77,77,.15); display:flex; align-items:center; justify-content:center; flex-shrink:0;"><svg width="15" height="15" viewBox="0 0 24 24" stroke="#FF4D4D" stroke-width="2.6" fill="none"><path d="M12 8v5m0 3h.01" stroke-linecap="round"/></svg></div><div style="font-size:14px; color:#e9e9ee; line-height:1.4;"><b>Refused a video call</b> to confirm the item exists</div></div>
            <div class="flag" data-animate style="display:flex; gap:12px; align-items:flex-start; padding:12px 0;"><div style="width:26px; height:26px; border-radius:8px; background:rgba(224,162,60,.16); display:flex; align-items:center; justify-content:center; flex-shrink:0;"><svg width="15" height="15" viewBox="0 0 24 24" stroke="#E0A23C" stroke-width="2.6" fill="none"><path d="M12 8v5m0 3h.01" stroke-linecap="round"/></svg></div><div style="font-size:14px; color:#e9e9ee; line-height:1.4;">Price is <b>40% below market</b> for this item</div></div>
          </div>
          <div style="margin:24px 22px; display:flex; gap:12px;"><div style="flex:1; height:56px; border-radius:14px; background:rgba(255,255,255,.06); border:1px solid #26262b; display:flex; align-items:center; justify-content:center; font-weight:700; font-size:15px; color:#e9e9ee;">Cancel deal</div><div style="flex:1; height:56px; border-radius:14px; background:rgba(255,77,77,.14); border:1px solid rgba(255,77,77,.4); display:flex; align-items:center; justify-content:center; font-weight:700; font-size:15px; color:#FF4D4D;">Pay anyway</div></div>
        </div>`;
