// Auto-generated from the TrustFlow design (screen "trust-low"). Do not hand-edit.
export const html = `<div class="fscroll" style="width:366px; height:820px; border-radius:42px; overflow-y:auto; overflow-x:hidden; position:relative; background:radial-gradient(120% 70% at 50% 0%, #0d2418 0%, #0B0B0D 55%);">
          <div style="height:44px; display:flex; align-items:center; justify-content:space-between; padding:0 26px; font-size:13px; font-weight:600;"><span>9:41</span><span style="opacity:.7;">▂▃▄ ᯤ ▮</span></div>
          <div style="padding:8px 22px 0; display:flex; align-items:center; gap:14px;"><div class="navbtn" data-nav="new-escrow" style="width:40px; height:40px; border-radius:12px; background:rgba(255,255,255,.06); display:flex; align-items:center; justify-content:center;"><svg width="18" height="18" viewBox="0 0 24 24" stroke="#fff" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round"><path d="M15 18l-6-6 6-6"/></svg></div><h2 style="font-size:20px; font-weight:800; letter-spacing:-.02em;">Trust Score</h2></div>
          <!-- big dial -->
          <div style="display:flex; flex-direction:column; align-items:center; margin-top:20px;">
            <div style="position:relative; width:210px; height:210px; animation:floaty 6s ease-in-out infinite;">
              <div class="ring low" data-animate style="position:absolute; inset:0; border-radius:50%; background:conic-gradient(#34D07E calc(var(--p)*3.6deg), rgba(255,255,255,.07) 0); box-shadow:0 0 50px -6px rgba(52,208,126,.4);"></div>
              <div style="position:absolute; inset:16px; border-radius:50%; background:radial-gradient(circle at 38% 30%, #14261d, #0B0B0D 70%); box-shadow:inset 0 6px 20px rgba(0,0,0,.7);"></div>
              <div style="position:absolute; top:34px; left:60px; width:70px; height:44px; border-radius:50%; background:radial-gradient(circle at 40% 30%, rgba(52,208,126,.35), transparent 70%); filter:blur(4px);"></div>
              <div style="position:absolute; inset:0; display:flex; flex-direction:column; align-items:center; justify-content:center;"><div class="score-num" data-countup="88" style="font-size:66px; font-weight:800; letter-spacing:-.05em; line-height:1; color:#fff;">0</div><div style="font-size:13px; color:#9A9AA0; margin-top:2px;">out of 100</div></div>
            </div>
            <div style="margin-top:18px; display:inline-flex; align-items:center; gap:8px; padding:9px 18px; border-radius:999px; background:rgba(52,208,126,.15); border:1px solid rgba(52,208,126,.4); color:#34D07E; font-size:14px; font-weight:800; letter-spacing:.02em;"><svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#34D07E" stroke-width="2.4"><path d="M20 6 9 17l-5-5" stroke-linecap="round" stroke-linejoin="round"/></svg>LOW RISK</div>
          </div>
          <!-- verdict -->
          <div style="margin:22px 22px 0; padding:16px; border-radius:18px; background:rgba(52,208,126,.08); border:1px solid rgba(52,208,126,.25);"><p style="font-size:15px; line-height:1.5; color:#d7f5e6; font-weight:600;">This seller looks safe. Established account and a calm, normal conversation — you can go ahead.</p></div>
          <!-- flags -->
          <div style="margin:20px 22px 0;"><div style="font-size:13px; font-weight:700; color:#9A9AA0; letter-spacing:.02em; margin-bottom:12px;">WHAT WE CHECKED</div>
            <div class="flag" data-animate style="display:flex; gap:12px; align-items:flex-start; padding:12px 0; border-bottom:1px solid #1a1a1e;"><div style="width:26px; height:26px; border-radius:8px; background:rgba(52,208,126,.15); display:flex; align-items:center; justify-content:center; flex-shrink:0;"><svg width="15" height="15" viewBox="0 0 24 24" stroke="#34D07E" stroke-width="2.6" fill="none"><path d="M20 6 9 17l-5-5" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div style="font-size:14px; color:#e9e9ee; line-height:1.4;">Account is <b>3 years old</b> with a verified phone number</div></div>
            <div class="flag" data-animate style="display:flex; gap:12px; align-items:flex-start; padding:12px 0; border-bottom:1px solid #1a1a1e;"><div style="width:26px; height:26px; border-radius:8px; background:rgba(52,208,126,.15); display:flex; align-items:center; justify-content:center; flex-shrink:0;"><svg width="15" height="15" viewBox="0 0 24 24" stroke="#34D07E" stroke-width="2.6" fill="none"><path d="M20 6 9 17l-5-5" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div style="font-size:14px; color:#e9e9ee; line-height:1.4;"><b>41 completed deals</b>, no disputes on record</div></div>
            <div class="flag" data-animate style="display:flex; gap:12px; align-items:flex-start; padding:12px 0;"><div style="width:26px; height:26px; border-radius:8px; background:rgba(52,208,126,.15); display:flex; align-items:center; justify-content:center; flex-shrink:0;"><svg width="15" height="15" viewBox="0 0 24 24" stroke="#34D07E" stroke-width="2.6" fill="none"><path d="M20 6 9 17l-5-5" stroke-linecap="round" stroke-linejoin="round"/></svg></div><div style="font-size:14px; color:#e9e9ee; line-height:1.4;">Chat was calm — <b>no pressure or rush language</b> detected</div></div>
          </div>
          <div class="navbtn" data-nav="fund" style="margin:24px 22px; height:56px; border-radius:14px; background:#E4144F; display:flex; align-items:center; justify-content:center; font-weight:700; font-size:16px;">Proceed to fund escrow</div>
        </div>`;
